### ISSUE TITLE
vertical scroll/drag

### ISSUE THREAD

**Issue by gitmegrub** [appintheair/react-native-looped-carousel#10]
Hi, have configured the carousel to have a width and height not equal to the screen size however, I can seem to drag the contents vertically. Is there a way to disable this?

I tried playing around the Scrollview props without any luck. 

This is probably related to RN bug https://github.com/facebook/react-native/issues/2127

G

**Comment by asamiller** [comment]
I ran into this issue and solved it by setting the height of the Carousel to be the same height as my inner contents: `<Carousel style={{height:300}}>`

**Comment by spronin** [comment]
yeah, you just set width / height for the Carousel and it should work

**Comment by gre** [comment]
I still feel this is a bug.
inner content that is higher that the carousel constraint should be allowed if I want to just "overflow:hidden" with the carousel height. Imagine if you do animation on carousel height, it's not performant to re-render all cells heights everytime the main height changes..
