### ISSUE TITLE
Icons and Text styles for arrows

### ISSUE THREAD

**Issue by gwenf** [appintheair/react-native-looped-carousel#108]
I was trying to change the styling for the arrows, but the way the code is written for this package, it only lets me change the `TouchableOpacity` and `View` tags that wrap the `Text` tag.

So, on lines 314 and 315 in the `index.js` file I added `style={this.props.leftStyle/rightStyle}`:

```js
<Text style={this.props.leftStyle}>{this.props.leftArrowText ? this.props.leftArrowText : 'Left'}</Text>
<Text style={this.props.rightStyle}>{this.props.rightArrowText ? this.props.rightArrowText : 'Right'}</Text>
```

Also, the README file says using icons are supported, but I don't see a way to do this with how the code is currently written. Am I missing something or is this something you would want to add?

**Comment by phil-r** [comment]
Hi @gwenf ,
I've never used this functionality myself, if you think that something is wrong/not working/not documented properly - feel free to submit a PR

**Comment by phil-r** [comment]
But just adding `leftArrowText` and `rightArrowText` properties with your icon component should work.

**Comment by gwenf** [comment]
`this.props.leftArrowText` works fine, but I want to change the styling for the Text; that's why I added the style attribute to `Text`.

I can submit a PR if you want.

**Comment by gwenf** [comment]
I forgot to update this. I am able to pass a custom component into leftArrowText and rightArrowText and that suits my needs. Thank you.
