### ISSUE TITLE
Cannot read property 'measure' of null

### ISSUE THREAD

**Issue by jsshizhan** [appintheair/react-native-looped-carousel#120]
<Carousel
          delay={2000}
          style={this.state.size}
          bullets
          chosenBulletStyle={{backgroundColor:COLOR.active}}
          bulletsContainerStyle={{backgroundColor:COLOR.white}}
          bulletsContainerStyle={{justifyContent:'flex-end'}}
          pageInfoBottomContainerStyle={{backgroundColor:COLOR.light_gray}}
          currentPage={1}>
          {this.carouselList()}
        </Carousel>

carouselList = () => {
        return this.state.advertTops.map((data)  => {
            return (<View style={styles.imageCell} key={data.id}>
                            <Image style={[styles.imageStyle,this.state.size]} source={{uri:`${SERVER.address}/file/${data.picture}`}}><Text>{data.title}</Text></Image>
                    </View>)
        })
  }

**Comment by bnerDY** [comment]
How do you solve this ?
