### ISSUE TITLE
Not working getting an error message

### ISSUE THREAD

**Issue by pramodmg** [appintheair/react-native-looped-carousel#14]
<img width="923" alt="screen shot 2015-11-02 at 11 16 48 am" src="https://cloud.githubusercontent.com/assets/10665538/10874986/45f89a3e-8153-11e5-9541-a0659d2b1174.png">

Can You please look into it.

Thanks in advance

**Comment by praisegeek** [comment]
+1. Experiencing the same issue.

**Comment by joeygaskin** [comment]
Also having the same issue. npm installed a few days or so ago and now its currently not working.

**Comment by spronin** [comment]
updated the repo. gonna update npm also

**Comment by joeygaskin** [comment]
Thanks!

**Comment by praisegeek** [comment]
It's actually an updated npm issue... Besides the output errors, the module still get installed. Check node_modules.
