### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by jfsemaan** [appintheair/react-native-looped-carousel#17]
Hi,

iOS works as expected, but Android has some issues. The loop doesn't work. Using 3 images it shows:
First pass: 1-2-3
Second Pass: 1-2-Stops

Also when I swipe the image to the right or to left, the next image doesn't move automatically to fit the screen. The transition stays in between the image before and the next one.

**Comment by rainbowhat** [comment]
How do you even install this thing?

**Comment by timzaak** [comment]
remove the `peer dependencies` in package.json
and because of some react-native apis are not usable in Android, it may not work as better as ios

**Comment by seb0zz** [comment]
Even this library works like a charm for iOS if you want to have it Android compatible right now I would suggest using [react-native-swiper](https://github.com/leecade/react-native-swiper)

**Comment by herby** [comment]
Close this?

**Comment by spronin** [comment]
We still need so work to do here, unfortunately ;(

**Comment by jjhargreaves** [comment]
@seb0zz: react-native-swiper also seems to lack endless scroll support/general support for Android if I'm not wrong, that's why I'm here 😂

**Comment by phil-r** [comment]
fixed by #37
