### ISSUE TITLE
get current View child

### ISSUE THREAD

**Issue by L-Jovi** [appintheair/react-native-looped-carousel#22]
I want to get current `<View />` child inside `Carousel` when it's looping,
is there any callback could help me?

thanks for your time.

**Comment by spronin** [comment]
@L-Jovi please check onAnimateNextPage callback prop on the carousel
you can get current page number (1-based). If you have a model outside you can map it to specific object, e.g. View

**Comment by L-Jovi** [comment]
@spronin  thanks for your reply :)
