### ISSUE TITLE
Source of example 

### ISSUE THREAD

**Issue by tomav** [appintheair/react-native-looped-carousel#23]
Hi, really nice work on this Carousel!

I was wondering if you could provide the source of the example displayed in the `README`.
You have the fullscreen carousel + static elements that don't move when you swipe.
React-native beginners like me will have a better understanding of how it works with it.

Thank you.

**Comment by spronin** [comment]
@tomav take a look at https://github.com/appintheair/react-native-buyscreen
There is example usage of the component as sees in the gif

**Comment by tomav** [comment]
I saw that, but it's a more basic version. :-)
I was wondering if you could provide the exact example you display as gif.

**Comment by phil-r** [comment]
@tomav https://github.com/appintheair/react-native-buyscreen is the exact example ;)
