### ISSUE TITLE
Please clarify why this is not recommended for RN0.24 or is just a typo?

### ISSUE THREAD

**Issue by rturk** [appintheair/react-native-looped-carousel#27]
HI,

According to package.json this repo is **not** compatible with RN 0.24 or this is just a typo (missing `<=`)?

  "peerDependencies": {
    "react-native": ">=0.16.0 <0.24"
  },

npm WARN react-native-looped-carousel@0.0.10 requires a peer of react-native@>=0.16.0 <0.24 but none was installed.

**Comment by phil-r** [comment]
The limit was removed, If you'll encounter any problems - please report

**Comment by rturk** [comment]
I'll run some tests!
