### ISSUE TITLE
There is rn 0.24 out

### ISSUE THREAD

**Issue by herby** [appintheair/react-native-looped-carousel#28]
Could you update deps if it works for that version and release 0.0.11 with `<0.25`? Thanks.

**Comment by herby** [comment]
(Is that '<xxx' needed at all? Isn't optimistic ">= only" with "we'll fix it once needed" easier solution for users? It stops my upgrade to rn 0.24 b/c npm shrinkwrap fails)

**Comment by phil-r** [comment]
Yeah I think `optimistic` solution is better, thanks
New version is published
