### ISSUE TITLE
The view doesn't refresh on landscape mode

### ISSUE THREAD

**Issue by maxs15** [appintheair/react-native-looped-carousel#3]
When passing from the portrait mode to the landscape mode the view doesn't resize the fetch the new screen size.

**Comment by phil-r** [comment]
@maxs15 thank you! We've tested only portrait mode, our bad ;(

**Comment by umair-khan1993** [comment]
So do you people plan on fixing this bug?

**Comment by spronin** [comment]
@maxs15 @umair-khan1993 check the readme
orientation changes can be handles using onLayout on parent view
