### ISSUE TITLE
FEATURE REQUEST: ability to pass index of child you want displayed first

### ISSUE THREAD

**Issue by stantoncbradley** [appintheair/react-native-looped-carousel#33]
I want to specify the initial view to display when rendering the carousel.

Thanks!

**Comment by phil-r** [comment]
fixed by #32 and #37 
https://github.com/appintheair/react-native-looped-carousel#props

**Comment by stantoncbradley** [comment]
fantastic thanks so much!  this has been a popular request from my users, can't wait to try it out!

**Comment by phil-r** [comment]
@stantoncbradley feel free to create new issues if there will be any problems wth the new version ;)
