### ISSUE TITLE
It looks like that the memory usage never stops increasing.

### ISSUE THREAD

**Issue by britzlieg** [appintheair/react-native-looped-carousel#35]
When I finished rendering the component , I just watch the memory usage and just do nothing.The memory usage is inscreasing second by second . Then after about 3 minutes , the memory usage is above 200M ! Is that a bug for this component , or not ? Thanks for your answer.

**Comment by phil-r** [comment]
Hi @britzlieg , sorry for the long reply. I wasn't able to repro on the Example after a couple of minutes memory actually reduced from ~76 to ~60 MB

if you have an example of code with the leak - I'l be happy to help.

![image](https://cloud.githubusercontent.com/assets/577316/19326108/8248f87c-90c9-11e6-8ecc-2402de04845a.png)
