### ISSUE TITLE
onMomentumScrollEnd undocumented

### ISSUE THREAD

**Issue by nvartolomei** [appintheair/react-native-looped-carousel#36]
I'm wondering where you found this prop?

**Comment by waleedarshad-vf** [comment]
https://github.com/appintheair/react-native-looped-carousel/search?utf8=%E2%9C%93&q=onMomentumScrollEnd :)

**Comment by phil-r** [comment]
fixed by #37 
https://github.com/appintheair/react-native-looped-carousel#props
