### ISSUE TITLE
Android paging block until going one page back

### ISSUE THREAD

**Issue by DeDuckProject** [appintheair/react-native-looped-carousel#50]
I have a 4 page carousel.
Sometimes, not always, on Android, when I try going forward, I get stuck after the 2nd page. only when I go back one step, and then forward again, I can go more step forward.
Also I get weird inconsistent jumps with the animation.

Here's how it looks:
![tutorialandroidbug](https://cloud.githubusercontent.com/assets/10045034/20499358/d5170fb4-b039-11e6-9d56-a02ce8897e67.gif)

my code:
```javascript
<Carousel
                    style={carouselStyle.carousel}
                    chosenBulletStyle={carouselStyle.chosenBullet}
                    bulletStyle={carouselStyle.bullet}
                    autoplay={false}
                    bullets={true}
                    pageInfo={false}
                    onAnimateNextPage={(p) => this.pageChange(p)}
                >
                    <FCarouselItem title={strings.tutorial.content[0].title} text={strings.tutorial.content[0].text} image={icons.logo_with_text}/>
                    <FCarouselItem style={{backgroundColor:FetchyColors.primaryColorAlpha}} title={strings.tutorial.content[1].title} text={strings.tutorial.content[1].text} image={icons.tutorial_fab_screen}/>
                    <FCarouselItem style={{backgroundColor:FetchyColors.primaryColorAlpha}} title={strings.tutorial.content[2].title} text={strings.tutorial.content[2].text} image={icons.delivery_add_screen}/>
                    <FCarouselItem style={{backgroundColor:FetchyColors.primaryColorAlpha}} title={strings.tutorial.content[3].title} text={strings.tutorial.content[3].text} image={icons.trip_add_screen}/>
                </Carousel>
```

this.pageChange(p) changes the bottom text with setState for the parent component, but even without this - the bug still occurs

**Comment by sudhanshu6247** [comment]
I am also facing the same problem. There are 3 pages in my carousel and it works fine till scrolling first page and reaching to second page. I get stuck after 2nd page. Please help.
Here is my code:
<Carousel
            delay={3000}
            style={this.state.size}
            autoplay={false}
            pageInfo
            onAnimateNextPage={(p,q,r) => {console.log(p,q,r);}}
          >

            <View style={[this.state.size]}><Image style={{width: deviceWidth, height: deviceHeight,}} source={require('../images/carousel1.png')} /></View>
            <View style={[this.state.size]}><Image style={{width: deviceWidth, height: deviceHeight,}} source={require('../images/carousel2.png')} /></View>
            <View style={[this.state.size]}><Image style={{width: deviceWidth, height: deviceHeight,}} source={require('../images/carousel3.png')} /></View>
          </Carousel>

**Comment by JasonFok** [comment]
Same

**Comment by dragonwong** [comment]
the same

**Comment by luco** [comment]
+1

**Comment by ammichael** [comment]
+1

**Comment by JasonFok** [comment]
+1 Works perfectly fine on iOS though

**Comment by Clowning** [comment]
I have almost the same problem ! When i have 3 screens, on the second, i can't swipe to the third ! But with the autoplay, it works ! :/ ! If you have a fix maybe?

**Comment by ammichael** [comment]
Hey guys, I've updated my react and react-native to the latest version (15.4.2 and 0.41.2 respectively
), and suddenly the bug is gone! 🎉

**Comment by Clowning** [comment]
Oh great :D ! I'm gonna test it ! :)

**Comment by ryanhomer** [comment]
@ammichael @Clowning Updating to RN 0.41.2 (from 0.41.0) with React 15.4.2 did **_not_** help alleviate the issue for me completely but it does seem to stick on page 2 (It's always on page 2) less frequently.

**Comment by ryanhomer** [comment]
After further investigation, it seems like this might be a core bug. I'm working exclusively with Android at the moment, so I'm guessing that this is in the ScrollView control on the Java side.

Let's say we have 4 pages, page 0 to page 3 (last page). Two additional pages will be created, page 4 = page 0, and page 5 = page 1.

If your initial page is page 0, a non-animated scroll will move you to page 4, allowing you to swipe left (to last page) or right (to page 5 == page 1).

If you then swipe right, you will move to page 5 (==page 1), then after the scroll has completed, a non-animated scroll will move you to page 1, again allowing you to scroll left (to page 0) or right (to page 2).

If you then swipe left, you will move to page 0, then after the scroll has completed, a non-animated scroll will move you to page 4 (==page 0).

In the last two scenarios above, the `_scrollTo` function is called to do this non-animated scroll. If you perform an **animated** scroll just after the non-animated scroll, this "fixes" the issue.

      _scrollTo = (offset, animated) => {
        if (this.scrollView) {
          this.scrollView.scrollTo({ y: 0, x: offset, animated });
          this.scrollView.scrollTo({ y: 0, x: offset, animated: true });
        }
      }

I will dig around on the Java side and see if I can find anything there.

**Comment by ammichael** [comment]
@ryanhomer Very nice debugging! hahaha

Hopefully you'll find and fix it, because I probably would take a full year to (not very skilled in Java).

Thanks for being so helpful already!

**Comment by DeDuckProject** [comment]
@ryanhomer Your fix works pretty good as a temp workaround for me at the moment..
Hope the solution is close :) 💃

**Comment by Clowning** [comment]
@ryanhomer  Thank dude :D !!!!!

**Comment by ryanhomer** [comment]
@ammichael @DeDuckProject @Clowning I've not been able to determine yet if this is fixable on the Java side. I managed to track down this piece of code in `node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollViewManager.java`:

    @Override
    public void scrollToEnd(
	    ReactScrollView scrollView,
	    ReactScrollViewCommandHelper.ScrollToEndCommandData data) {
		// ScrollView always has one child - the scrollable area
		int bottom =
	    scrollView.getChildAt(0).getHeight() + scrollView.getPaddingBottom();
		if (data.mAnimated) {
	    scrollView.smoothScrollTo(scrollView.getScrollX(), bottom);
		} else {
	    scrollView.scrollTo(scrollView.getScrollX(), bottom);
		}
    }

ReactScrollView is defined in `ReactScrollView.java` (same directory) and extends `android.widget.ScrollView` so I don't know that there's much, if anything, that can be done.

Well, at least I see that the workaround has been checked in and merged. So far it seems to be holding up well.

Cheers!
