### ISSUE TITLE
React.Children.only expected to receive a single React element child

### ISSUE THREAD

**Issue by cheshuangchun** [appintheair/react-native-looped-carousel#64]
This is my code
render()
	{
		return(
			<View style = {{height:this.state.pHeight}}>
				<Carousel
					delay={2000}
					style={{flex:1}}
					autoplay
					bullets
				>
					{this.renderImg()}
					</Carousel>
			</View>
		);
	}

renderImg(){
        var imageViews=[];
        for(var i=0;i<this.state.adList.length;i++){
            imageViews.push(
                <Image
                	key={i}
                    style={{height: this.state.pHeight,
						resizeMode: 'stretch',
						width:common.screenWidth}}
                    source={{uri:this.state.adList[i]}}
                    />
            );
        }
        return imageViews;
    }

so ,the question is  "React.Children.only expected to receive a single React element child"

**Comment by anders-g-hansen** [comment]
I was also seeing this issue.  The problem occurred when my dynamic content (imageViews for you) was a length of 1.  Just opened PR #66 that fixed this for me.

**Comment by viktorsec** [comment]
This issue has been fixed.
