### ISSUE TITLE
undefined is not an object error with the master branch code

### ISSUE THREAD

**Issue by ghprud** [appintheair/react-native-looped-carousel#70]
I am having issues loading my app with the code from master branch. The app shows an error "undefined is not an object (evaulating '_react2.default.propTypes.oneOfType')". I need the latest code as one of the issues I was having is fixed in the latest commit. Please let me know how soon this can be fixed. 

Thanks!
<img width="398" alt="screen shot 2017-02-23 at 1 46 35 pm" src="https://cloud.githubusercontent.com/assets/3988059/23280656/f0b8e0ce-f9ce-11e6-85f6-c85f292d6e42.png">

**Comment by viktorsec** [comment]
This has been fixed in the mean time.
