### ISSUE TITLE
crash when carousel only has one child

### ISSUE THREAD

**Issue by xjrad** [appintheair/react-native-looped-carousel#79]
here is my code:

let images = []
......some dynamic images operation
<Carousel
                        style={{width: WIN_WIDTH, height: WIN_HEIGHT, backgroundColor: 'rgba(0, 0, 0, 0.6)'}}
                        currentPage={this.state.selectIndex}
                        autoplay={false}
                        pageInfo={true}
                        pageInfoBackgroundColor='rgba(0,0,0,0.8)'
                        pageInfoTextStyle={{color: '#FFFFFF'}}
                        onAnimateNextPage={(p) => {
                            this.state.selectIndex = p
                        }}
                    >
                        {images}
< /Carousel>

the images array will add or reduce,when only has one element,the carousel crash

please help me out,thanks a lot

error stacks:
React.Children only expected to receive a sing React element child

**Comment by viktorsec** [comment]
We have the same problem.

**Comment by ChangeSomeCode** [comment]
+1

**Comment by dxiao** [comment]
Already fixed in #66 , just needs to be published to npm.

**Comment by wuyunqiang** [comment]
i know it .
react-native-looped-carousel /index.js
TouchableWithoutFeedback change to TouchableOpacity.
it's ok.

**Comment by phil-r** [comment]
Should be fixed by #67
