### ISSUE TITLE
Android not respecting currentPage

### ISSUE THREAD

**Issue by dxiao** [appintheair/react-native-looped-carousel#81]
It seems like when using the library on android, the currentPage property is not properly respected. Regardless of what you set for current page, it always goes to the first page. Moreover, it's not position `childrenLength * width`, but just `0`, which means you have to page 2 pages over before you can scroll backwards.

This seems to be due to https://github.com/facebook/react-native/issues/6849

Workaround seems to be putting _onLayout()'s call of _placeCritical() behind a setTimeout() callback, so that the scrollView.scrollTo() happens after the pages have been rendered.

RN 0.43, looped-carousel 0.1.5

**Comment by viktorsec** [comment]
The fix was merged, thank you!
